
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.util.Calendar;
import java.util.GregorianCalendar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohak
 */
public class ShoppingCart extends javax.swing.JFrame {

    /**
     * Creates new form ShoppingCart
     */
    public ShoppingCart() {
        
        initComponents();
        java.util.Date  f =new java.util.Date();
        GregorianCalendar c = new GregorianCalendar(f.getYear()+1900, f.getMonth()+1, f.getDate());
        String newDate=c.get(Calendar.DAY_OF_MONTH)+"/"+c.get(Calendar.MONTH)+"/"+c.get(Calendar.YEAR);
        curdate.setText(newDate+"");
        
        cust.setText(User.custID);
        cust.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bn = new javax.swing.JTextField();
        q = new javax.swing.JTextField();
        minus = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cart = new javax.swing.JTable();
        ps = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        curdate = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pa = new javax.swing.JTextField();
        removeCart = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cust = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Book Store");

        jLabel2.setText("Book Name");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Name", "Authour Name", "Pages", "Price", "Available Quantity"
            }
        ));
        tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMouseClicked(evt);
            }
        });
        tab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tabKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tab);

        jLabel3.setText("Quantity");

        jLabel4.setText("Order Details");

        jLabel5.setText("Name");

        bn.setEditable(false);

        q.setText("0");
        q.setEnabled(false);
        q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qActionPerformed(evt);
            }
        });

        minus.setText("-");
        minus.setEnabled(false);
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });

        plus.setText("+");
        plus.setEnabled(false);
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        jLabel6.setText("Cost of Book");

        cart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ItemName", "Quantity", "Price"
            }
        ));
        cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(cart);

        ps.setEditable(false);

        jButton4.setText("Add to cart");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        curdate.setText("Date");

        jButton5.setText("Logout");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel7.setText("Cart Total");

        pa.setEditable(false);
        pa.setText("0");

        removeCart.setText("Remove from Cart");
        removeCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCartActionPerformed(evt);
            }
        });

        jButton2.setText("Place Order");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cust.setText("Customer ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(111, 111, 111)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(minus)
                                        .addGap(13, 13, 13)
                                        .addComponent(q, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(plus))
                                    .addComponent(bn)
                                    .addComponent(ps))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(removeCart, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton4)
                                        .addGap(66, 66, 66)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(pa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(216, 216, 216))
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(curdate, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel2)
                        .addGap(170, 170, 170)
                        .addComponent(bname, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cust)
                .addGap(39, 39, 39)
                .addComponent(jButton5)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(437, 437, 437)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(cust))
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(curdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(bn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(q, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minus)
                            .addComponent(plus)
                            .addComponent(jButton4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(ps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removeCart)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Clear the table
        DefaultTableModel model = (DefaultTableModel) tab.getModel();
        model.setRowCount(0);
        
        //Adding in an Array
        ArrayList<User> userlist = new ArrayList<>();
        
        try{
            Class.forName("java.sql.DriverManager");
            //connect with mysql
            java.sql.Connection c= java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms","root","root");
            //create statement
            java.sql.Statement s= c.createStatement();
            //execute query
            java.sql.ResultSet h = s.executeQuery("select * from main where bookname like '%"+bname.getText()+"%'");
            
            User user;

        while(h.next()){
            user = new User(h.getString("bookname"),h.getString("authorname"),h.getInt("pages"),h.getFloat("sellingprice"),h.getInt("units"));
            userlist.add(user);
        }
        barr(userlist);
                    
        }catch(Exception e){
        javax.swing.JOptionPane.showMessageDialog(this, "Error;" + e);
    }
        
        //Displaying in table
    ArrayList<User> list = userlist;
    //DefaultTableModel model = (DefaultTableModel) tab.getModel();
    Object [] row = new Object[5];
    for(int i=0; i<list.size(); i++){
        row[0] = list.get(i).getBookn();
        row[1] = list.get(i).getAname();
        row[2] = list.get(i).getPage();
        row[3] = list.get(i).getSp();
        row[4] = list.get(i).getUnit();
        
        model.addRow(row);
        
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void barr(ArrayList<User> list){
        String[] barr = new String [list.size()];
        float [] parr = new float [list.size()];
        for(int i=0; i<list.size(); i++){
            barr[i] = list.get(i).getBookn();
            parr[i] = list.get(i).getSp();
        }
        User.b = barr;
        User.p = parr;
}
    
    private void tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseClicked
        // TODO add your handling code here:
        minus.setEnabled(true);
        plus.setEnabled(true);
        q.setEnabled(true);
        
        //Mouse click event
        //index of selected row
        int val = tab.getSelectedRow();
        bn.setText(User.b[val]);
        ps.setText(User.p[val]+"");
        q.setText(0+"");
        
    }//GEN-LAST:event_tabMouseClicked

    private void qActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        // TODO add your handling code here:
        int qu = Integer.parseInt(q.getText());
        if(qu>0){
            qu--;
        }    
        q.setText(qu+"");
        
    }//GEN-LAST:event_minusActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        // TODO add your handling code here:
        int qu = Integer.parseInt(q.getText());
        qu++;   
        q.setText(qu+"");
        
    }//GEN-LAST:event_plusActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String name = bn.getText();
        int quan = Integer.parseInt(q.getText());
        float pr = Float.parseFloat(ps.getText());
        DefaultTableModel model = (DefaultTableModel) cart.getModel();
        
        ArrayList<cart> cartItem = new ArrayList<>();
        cart c;
        c = new cart(name, quan, pr);
        cartItem.add(c);
        
        Object [] row = new Object[3];
    for(int i=0; i<cartItem.size(); i++){
        row[0] = cartItem.get(i).getBookn();
        row[1] = cartItem.get(i).getUnit();
        float p = cartItem.get(i).getUnit()*cartItem.get(i).getSp();
        //row[2] = cartItem.get(i).getSp();
        row[2]= p;
        model.addRow(row);
        float price = Float.parseFloat(pa.getText());
        price=price+p;
        pa.setText(price+"");
        
    }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tabKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabKeyPressed
        // TODO add your handling code here:
        //nothing
    }//GEN-LAST:event_tabKeyPressed

    private void tabKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabKeyReleased
        // TODO add your handling code here:
        ///nothing
    }//GEN-LAST:event_tabKeyReleased

    private void tabKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabKeyTyped
        // TODO add your handling code here:
        //nothing
    }//GEN-LAST:event_tabKeyTyped

    private void removeCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCartActionPerformed
        // TODO add your handling code here:
        //Remove from cart
        DefaultTableModel model = (DefaultTableModel) cart.getModel();
        ArrayList<cart> cartItem = new ArrayList<>();
        cart c;
        int r = cart.getSelectedRow();
        System.out.println(r);
        float p=0, price;
        Object [] row = new Object[3];
    for(int i=0; i<cartItem.size(); i++){
        row[0] = cartItem.get(i).getBookn();
        row[1] = cartItem.get(i).getSp();
        row[2] = cartItem.get(i).getUnit();
    }
    
    p=(float)model.getValueAt(r, 2);
    //System.out.println(p);
    model.removeRow(r);
    
    price = Float.parseFloat(pa.getText());
    price = price - p;
    pa.setText(price+"");
        
    }//GEN-LAST:event_removeCartActionPerformed

    private void cartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartMouseClicked
        // TODO add your handling code here:
        //mouse click cart
      
    }//GEN-LAST:event_cartMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        this.setVisible(false);
                
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int[] quan = new int[20];
        String[] name = new String[900];
        int id=0;
        String cdate = curdate.getText();
        int cid = Integer.parseInt(cust.getText());
        float p = Float.parseFloat(pa.getText());
        int flag=0;
        
        
        try{
            Class.forName("java.sql.DriverManager");
            //connect with mysql
            java.sql.Connection c= java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms","root","root");
            //create statement
            java.sql.Statement s= c.createStatement();
            //execute query
            
            DefaultTableModel model = (DefaultTableModel) cart.getModel();
            
            for(int i=0; i<model.getRowCount(); i++){
                quan[i] = (int) model.getValueAt(i, 1);
                name[i] = (String) model.getValueAt(i, 0);
                
                java.sql.ResultSet h = s.executeQuery("select units from main where bookname='"+name[i]+"'");
                if(h.next()){
                    int temp = Integer.parseInt(h.getString(1));
                    temp = temp-quan[i];
                    if(temp>=0){
                        //javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid quanity");
                        int k = s.executeUpdate("update main set units = '"+temp+"' where bookname = '"+name[i]+"' ");
                        java.sql.ResultSet q = s.executeQuery("select max(orderid) from orderdetails");
                        q.next();
                        String t = q.getString(1);
                        if(t.equals("Null"))
                            id = 0;
                        else{
                            id=Integer.parseInt(t);
                            id++;
                        }
                        int j = s.executeUpdate("insert into orderdetails values('"+id+"','"+cdate+"','"+cid+"','"+name[i]+" ("+quan[i]+")','"+p+"')");
                        if(j>0){
                            if(flag==0){
                            javax.swing.JOptionPane.showMessageDialog(this, "Order Placed, Check your email for more information");
                            flag=1;
                            }
                        }else{
                            javax.swing.JOptionPane.showConfirmDialog(this, "Your Order could not be placed right now.\nPlease try again later.");
                        }
                        
                    }else{
                        javax.swing.JOptionPane.showMessageDialog(this, "Order quantity invalid. Please select a lower quantity and try again.");
                    }
                }else{
                    javax.swing.JOptionPane.showMessageDialog(this, "Book not found.");
                }
            } 
        }catch(Exception e){
        javax.swing.JOptionPane.showMessageDialog(this, "Error;" + e);
    }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShoppingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShoppingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShoppingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShoppingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShoppingCart().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bn;
    private javax.swing.JTextField bname;
    private javax.swing.JTable cart;
    private javax.swing.JTextField curdate;
    private javax.swing.JLabel cust;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton minus;
    private javax.swing.JTextField pa;
    private javax.swing.JButton plus;
    private javax.swing.JTextField ps;
    private javax.swing.JTextField q;
    private javax.swing.JButton removeCart;
    private javax.swing.JTable tab;
    // End of variables declaration//GEN-END:variables
}
